imports:
    - { resource: "@BitBagSyliusAgreementPlugin/Resources/config/resources.yaml" }
    - { resource: "@BitBagSyliusAgreementPlugin/Resources/config/grids/*/*.yaml" }
    - { resource: "@BitBagSyliusAgreementPlugin/Resources/config/services.xml" }

bit_bag_sylius_agreement:
    modes:
        - required_and_non_cancellable
        - required
        - only_show
        - not_required
    contexts:
        registration_form:
            - Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
twig:
    form_themes:
        - '@BitBagSyliusAgreementPlugin/Form/agreement_approval_widget.html.twig'
