sylius_resource:
  resources:
    bitbag_sylius_agreement_plugin.agreement_history:
      driver: doctrine/orm
      classes:
        model: BitBag\SyliusAgreementPlugin\Entity\Agreement\AgreementHistory
        repository: BitBag\SyliusAgreementPlugin\Repository\AgreementHistoryRepository
