bitbag_sylius_agreement_plugin_admin_agreement:
  resource: |
    alias: bitbag_sylius_agreement_plugin.agreement
    section: admin
    templates: '@SyliusAdmin/Crud'
    redirect: update
    grid: bitbag_sylius_agreement_plugin_admin_agreement
    permission: true
    vars:
        all:
            subheader: bitbag_sylius_agreement_plugin.ui.manage_agreements
            templates:
                form: "@BitBagSyliusAgreementPlugin/Admin/Form/_form.html.twig"
        index:
            icon: 'file alternate outline'
  type: sylius.resource

bitbag_sylius_agreement_plugin_admin_agreement_archive:
  path: /agreements/{id}/archive
  methods: [PATCH]
  defaults:
    _controller: bitbag_sylius_agreement_plugin.controller.agreement::updateAction
    _sylius:
      section: admin
      permission: true
      form:
        type: Sylius\Bundle\ResourceBundle\Form\Type\ArchivableType
      redirect:
        route: referer
        parameters: {}

bitbag_sylius_agreement_plugin_ajax_by_name_phrase:
  path: /agreement/search
  methods: [GET]
  defaults:
    _controller: bitbag_sylius_agreement_plugin.controller.agreement::indexAction
    _format: json
    _sylius:
      serialization_groups: [Default]
      permission: true
      repository:
        method: findByNamePart
        arguments:
          phrase: $phrase
          locale: null
          limit: 25
